import React from 'react';
import { MixEvent, MixEventType } from '../types';

interface SavedMixModalProps {
  log: MixEvent[];
  onClose: () => void;
  title?: string;
}

const getEmojiForType = (type: MixEventType) => {
    switch (type) {
        case MixEventType.SONG_PLAY: return '🎵';
        case MixEventType.DJ_COMMENTARY: return '💬';
        case MixEventType.SOUND_EFFECT: return '💥';
        case MixEventType.SONG_REQUEST: return '🙋';
        case MixEventType.SONG_SUGGESTION: return '🤖';
        case MixEventType.SONG_REMOVED: return '🗑️';
        default: return '➡️';
    }
}

const SavedMixModal: React.FC<SavedMixModalProps> = ({ log, onClose, title }) => {
    
  const handleDownload = () => {
    const fileTitle = `DJ Verchual Mix - ${new Date().toLocaleDateString()}`;
    let content = `${fileTitle}\n====================================\n\n`;

    log.forEach(event => {
      const time = `[${event.timestamp.toLocaleTimeString()}]`;
      const type = `[${event.type}]`;
      content += `${time} ${type.padEnd(17, ' ')} ${event.content}\n`;
    });

    content += "\n====================================\nGenerated by DJ Verchual";

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `dj_verchual_mix_${Date.now()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };
    
  return (
    <div className="fixed inset-0 bg-black bg-opacity-75 flex items-center justify-center z-50 p-4">
      <div className="bg-gray-800 rounded-lg shadow-2xl max-w-2xl w-full max-h-[80vh] flex flex-col border border-purple-500/50">
        <div className="p-4 border-b border-gray-700 flex justify-between items-center">
          <h2 className="text-2xl font-bold text-purple-400">{title || 'Your Saved Mix'}</h2>
          <button onClick={onClose} className="text-gray-400 hover:text-white text-3xl leading-none">&times;</button>
        </div>
        <div className="p-6 overflow-y-auto">
          <ul className="space-y-4">
            {log.map((event, index) => (
              <li key={index} className="flex items-start gap-4">
                <span className="text-2xl">{getEmojiForType(event.type)}</span>
                <div className="flex-1">
                    <p className="font-semibold text-gray-200">{event.content}</p>
                    <p className="text-xs text-gray-500">
                        {event.timestamp.toLocaleTimeString()}
                    </p>
                </div>
              </li>
            ))}
          </ul>
        </div>
        <div className="p-4 border-t border-gray-700 flex justify-between items-center">
            <button
                onClick={handleDownload}
                className="bg-purple-600 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded-md transition-colors flex items-center gap-2"
            >
              <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path fillRule="evenodd" d="M3 17a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm3.293-7.707a1 1 0 011.414 0L9 10.586V3a1 1 0 112 0v7.586l1.293-1.293a1 1 0 111.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z" clipRule="evenodd" />
              </svg>
              Download Mix
            </button>
            <button
                onClick={onClose}
                className="bg-cyan-600 hover:bg-cyan-700 text-white font-bold py-2 px-4 rounded-md transition-colors"
            >
                Close
            </button>
        </div>
      </div>
    </div>
  );
};

export default SavedMixModal;